/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#003670",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "surface-bright": "#f8f9fa",
        "inverse-primary": "#88d982",
        "outline-variant": "#bfcaba",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#3e4a41",
        "tertiary-fixed-dim": "#bdcabe",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed": "#002204",
        "on-tertiary-fixed": "#131e17",
        "on-surface": "#191c1d",
        "on-primary-fixed-variant": "#005312",
        "surface-dim": "#d9dadb",
        "primary": "#0d631b",
        "primary-container": "#2e7d32",
        "primary-fixed-dim": "#88d982",
        "error-container": "#ffdad6",
        "on-surface-variant": "#40493d",
        "background": "#f8f9fa",
        "on-secondary-fixed-variant": "#00468c",
        "tertiary": "#4d5950",
        "surface-tint": "#1b6d24",
        "outline": "#707a6c",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-error-container": "#93000a",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "error": "#ba1a1a",
        "primary-fixed": "#a3f69c",
        "secondary": "#005db7",
        "tertiary-fixed": "#d9e6da",
        "tertiary-container": "#657167",
        "on-tertiary": "#ffffff",
        "secondary-container": "#64a1ff",
        "on-primary-container": "#cbffc2",
        "on-secondary-fixed": "#001b3d",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-container": "#e8f5e9",
        "on-primary": "#ffffff",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "secondary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#a9c7ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "32px",
        "gutter": "16px",
        "container-max": "1200px",
        "md": "16px",
        "sm": "8px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "xs": "4px",
        "base": "8px",
        "lg": "24px"
      },
      fontFamily: {
        "outfit": ["Outfit", "sans-serif"],
        "sora": ["Sora", "sans-serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
